admin/protected/modules/catalog/models/Catalog.php
<?php

/**
 * This is the model class for table "catalog".
 *
 * The followings are the available columns in table 'catalog':
 * @property integer $id
 * @property string $name
 * @property string $url
 * @property integer $seo_id
 */
class Catalog extends CActiveRecord
{
	
	public $childs;
	
	/**
	 * Returns the static model of the specified AR class.
	 * @param string $className active record class name.
	 * @return Catalog the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}

	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'catalog';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('name', 'required'),
			array('seo_id', 'numerical', 'integerOnly'=>true),
			array('name, url', 'length', 'max'=>50),
			// The following rule is used by search().
			// Please remove those attributes that should not be searched.
			array('id, name, url, seo_id', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
				'category'=>array(self::HAS_MANY, 'Category', 'catalog_id'),
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id' => 'ID',
			'name' => 'Название',
			'url' => 'Url',
			'seo_id' => 'Seo',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 * @return CActiveDataProvider the data provider that can return the models based on the search/filter conditions.
	 */
	public function search()
	{
		// Warning: Please modify the following code to remove attributes that
		// should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('id',$this->id);
		$criteria->compare('name',$this->name,true);
		$criteria->compare('url',$this->url,true);
		$criteria->compare('seo_id',$this->seo_id);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}
	
	static function getAllCatalogs(){
		$catalogs=self::model()->with('category')->findAll();
		$categories=Category::model()->findAll();
		for ($i=0;$i<count($catalogs);$i++){
			$catalogs[$i]->getAllChilds($categories);
		}
		return $catalogs;
	}
	
	function getAllChilds($categories=null){
		if(!$categories){
			$categories=Category::model()->findAll();
		}
		$res=array();
		for($i=0;$i<count($categories);$i++){
			if($categories[$i]->catalog_id==$this->id && $categories[$i]->parent_category==0){
				$childs=$categories[$i]->getChilds($categories);
				$categories[$i]->childs=$childs;
				$res[]=$categories[$i];
			}
		}
		$this->childs=$res;
	}
	
	static function getCatalogs(){
		return self::model()->findAll();
	}
	
	static function getSelectedCatalog(&$catalogs, $catalogid) {
		$selCatalog=null;
		for ( $i = 0; $i < count( $catalogs ); $i++ ) {
			if( $catalogs[$i]->id === $catalogid ) {
				$selCatalog = $catalogs[$i];
				unset( $catalogs[$i] );
				break;
			}
		}
		if( $selCatalog == null && count( $catalogs ) > 0 ){
			$selCatalog = $catalogs[0];
			unset( $catalogs[0] );
		}
		return $selCatalog;
	}
	
}

admin/protected/modules/catalog/controllers/CatalogController.php
<?php

class CatalogController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			'postOnly + delete', // we only allow deletion via POST request
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('index'),
				'users'=>array('*'),
			),
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array('create','update'),
				'users'=>array('*'),
			),
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions'=>array('delete'),
				'users'=>array('*'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new Catalog;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Catalog']))
		{
			$model->attributes=$_POST['Catalog'];
			if($model->save())
				$this->redirect(array('index'));
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Catalog']))
		{
			$model->attributes=$_POST['Catalog'];
			if($model->save())
				$this->redirect(array('index'));
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		$model=$this->loadModel($id);
		if($model){
			$criteria=new CDbCriteria();
			$criteria->addCondition('catalog_id = :cid');
			$criteria->params=array(':cid'=>$model->id);
			$catalogs=Category::model()->findAll($criteria);
			for($i=0;$i<count($catalogs);$i++){
				$catalogs[$i]->delete();
			}
			$model->delete();
		} else {
			$this->render('application.views.site.error2', array('message'=>'не то удаляемс'));
		}

		// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
		if(!isset($_GET['ajax']))
			$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex($catalog=1)
	{
		$catalogs=Catalog::getAllCatalogs();
		$this->render('index', array('catalogs'=>$catalogs));
	}

	/**
	 * Manages all models.
	 */
	

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer the ID of the model to be loaded
	 */
	public function loadModel($id)
	{
		$model=Catalog::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param CModel the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='catalog-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
	
	
}

admin/protected/modules/catalog/controllers/CategoryController.php
<?php

class CategoryController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			'postOnly + delete', // we only allow deletion via POST request
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('index','view'),
				'users'=>array('@'),
			),
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array('create','update'),
				'users'=>array('@'),
			),
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions'=>array('delete'),
				'users'=>array('@'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate($catalog=1)
	{
		$model=new Category;
		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);
		$catalog=Catalog::model()->findByPk($catalog);
		if(!$catalog){
			$this->render('application.views.site.error2', array('message'=>'родительская категория не существует'));
		}
		//$categories=Category::getCategories($catalog->id);
		$catalogs=Catalog::getAllCatalogs();
		$selCatalog=Catalog::getSelectedCatalog($catalogs, $catalog->id);
		$model->catalog_id=$catalog->id;
		if(isset($_POST['Category']))
		{
			$model->attributes=$_POST['Category'];
			$model->img1=CUploadedFile::getInstance($model,'image1');
			if($model->img1){
				$length = 15;
				$chars = array_merge(range(0,9), range('a','z'), range('A','Z'));
				shuffle($chars);
				$name = implode(array_slice($chars, 0, $length));
				$model->image1=$name.'.'.$model->img1->getExtensionName();
			}
			if(isset($model->name_lang1)){
				if(empty($model->name_lang2)){
					$model->name_lang2=$model->name_lang1;
				}
				if(empty($model->name_lang3)){
					$model->name_lang3=$model->name_lang1;
				}
			} 
			
			if($model->save()){
				if($model->img1){
					$model->img1->saveAs(realpath(Yii::getPathOfAlias('webroot').'/../images/catalog').'/'.$model->image1);
					$ih = new CImageHandler();
					Yii::app()->ih->load(realpath(Yii::getPathOfAlias('webroot').'/../images/catalog').'/'.$model->image1)->
					thumb('300', false)->
					save(realpath(Yii::getPathOfAlias('webroot').'/../images/catalog/medium').'/'.$model->image1);
				}
				$this->redirect(array('/catalog/category/index', 'catalog'=>$selCatalog->id));
			}
		}
		
		$counts=Category::getCounts( $catalog->id );
		$this->render('create',array(
			'model'=>$model,
			//'categories'=>$categories,
			//'catalog'=>$catalog,
			'selCatalog'=>$selCatalog,
			'catalogs'=>$catalogs,
			'counts'=>$counts,
		));
	}
	
	
	public function actionView($id, $show=null)
	{
		$prods=Product::getProducts($id, $show);
		$counts=Product::getCounts($id);
		$category=Category::model()->with('catalog')->findByPk($id);
		if($category){
			$categorys=Category::getCategories($category->catalog->id);
			$selCategory=Category::getSelectedCategoru($categorys, $category->id);
			$leftMenu=Product::getLeftMenu($categorys, $selCategory, $counts);
			$this->render('view',array(
				'model'=>$category,
				'prods'=>$prods,
				'catalog'=>$category->catalog,
				'leftMenu'=>$leftMenu,
			));
		} else {
			$this->redirect(array('/catalog/category/index', 'ebaldos'=>1));
		}
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);
		
		
		$oldimg1=$model->image1;

		if(isset($_POST['Category']))
		{
			$model->attributes=$_POST['Category'];
			$model->img1=CUploadedFile::getInstance($model,'image1');
			if($model->img1){
				$length = 15;
				$chars = array_merge(range(0,9), range('a','z'), range('A','Z'));
				shuffle($chars);
				$name = implode(array_slice($chars, 0, $length));
				$model->image1=$name.'.'.$model->img1->getExtensionName();
			} else {
				$model->image1=$oldimg1;
			}
			if(isset($model->name_lang1)){
				if(empty($model->name_lang2)){
					$model->name_lang2=$model->name_lang1;
				}
				if(empty($model->name_lang3)){
					$model->name_lang3=$model->name_lang1;
				}
			}
			
			if($model->save()){
				if($model->img1){
					$model->img1->saveAs(realpath(Yii::getPathOfAlias('webroot').'/../images/catalog').'/'.$model->image1);
					$ih = new CImageHandler();
					Yii::app()->ih->load(realpath(Yii::getPathOfAlias('webroot').'/../images/catalog').'/'.$model->image1)->
					thumb('300', false)->
					save(realpath(Yii::getPathOfAlias('webroot').'/../images/catalog/medium').'/'.$model->image1);
				}
				$this->redirect(array('/catalog/category/index', 'catalog'=>$model->catalog_id));
			}
		}
		$counts=Category::getCounts($model->catalog_id);
		$catalogs=Catalog::getAllCatalogs();
		$selCatalog=Catalog::getSelectedCatalog($catalogs, $model->catalog_id);
		$this->render('update',array(
			'model'=>$model,
			'counts'=>$counts,
			'catalogs'=>$catalogs,
			'selCatalog'=>$selCatalog,
		));
	}
	
	function actionIndex($catalog=1, $show=null){
		$catalogs = Catalog::getAllCatalogs();
		$selCatalog=Catalog::getSelectedCatalog($catalogs, $catalog);
		
		if (!empty( $selCatalog ) ){
			$counts=Category::getCounts( $selCatalog->id );
			$categories=Category::getCategories($selCatalog->id, $show);
		} else {
			$counts=Category::getCounts( 0 );
			$categories=Category::getCategories(0, $show);
		}
		
		
		$this->render('index',array(
				'categories'=>$categories,
				'counts'=>$counts,
				'catalogs'=>$catalogs,
				'selCatalog'=>$selCatalog,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		$category=$this->loadModel($id);
		$catalogid=$category->catalog_id;
		$category->delete();

		// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
		if(!isset($_GET['ajax']))
			$this->redirect(array('/catalog/category/index', 'catalog'=>$catalogid));
	}

	/**
	 * Lists all models.
	 */

	/**
	 * Manages all models.
	 */

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer the ID of the model to be loaded
	 */
	public function loadModel($id)
	{
		$model=Category::model()->with('catalog')->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param CModel the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='category-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

admin/protected/modules/catalog/views/catalog/_catalogLine.php
<?php
echo '<tr>
									<td>'.$num.'</td>
									<td>'.$catalog->name.'</td>
									<td>
										<a href="'.CHtml::normalizeUrl(array('category/create', 'catalogid'=>$catalog->id)).'" class="rewiew"></a>
										<a href="'.CHtml::normalizeUrl(array('catalog/update', 'id'=>$catalog->id)).'" class="edit"></a>
										'.CHtml::link('',array('catalog/delete', 'id'=>$catalog->id), array(
    'submit'=>array('catalog/delete', 'id'=>$catalog->id),
    'class' => 'delete','confirm'=>'This will remove the catalog. Are you sure?'
  )).'
									</td>
								</tr>';
if(count($catalog->childs)){
	$childs=$catalog->childs;
	for($i=0;$i<count($childs);$i++){
		echo $this->renderPartial('_categoryLine', array('category'=>$childs[$i], 'num'=>$num.'.'.($i+1)));
	}
}

admin/protected/modules/catalog/views/catalog/_categoryLine.php
<?php
echo '<tr>
									<td class="level2">'.$num.'</td>
									<td class="level2">'.$category->name.'</td>
									<td>
										<a href="#" class="rewiew"></a>
										<a href="'.CHtml::normalizeUrl(array('category/update', 'id'=>$category->id)).'" class="edit"></a>
										'.CHtml::link('',array('category/delete', 'id'=>$category->id), array(
    'submit'=>array('category/delete', 'id'=>$category->id),
    'class' => 'delete','confirm'=>'This will remove the image. Are you sure?'
  )).'
									</td>
								</tr>';

admin/protected/modules/catalog/views/catalog/_form.php
<?php
/* @var $this CatalogController */
/* @var $model Catalog */
/* @var $form CActiveForm */
?>

<div class="conteiner">

<?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'catalog-form',
	'enableAjaxValidation'=>false,
)); ?>


	<?php echo $form->errorSummary($model); ?>

	<div class="conteiner">
	<div class="left">
	<div class="form_title">
		<?php echo $model->attributeLabels()['name'] ?>
	</div>
	</div>
	<div class="center">
	<div class="form_input">
		<?php echo $form->textField($model,'name',array('size'=>50,'maxlength'=>50, 'class'=>"small")); ?>
	</div>
		<?php echo $form->error($model,'name'); ?>
	</div>
	</div>

	<div class="conteiner">
	<div class="left">
	<div class="form_title">
		<?php echo $model->attributeLabels()['url'] ?>
	</div>
	</div>
	<div class="center">
	<div class="form_input">	
		<?php echo $form->textField($model,'url',array('size'=>50,'maxlength'=>50, 'class'=>'small')); ?>
	</div>
		<?php echo $form->error($model,'url'); ?>
	</div>
	</div>

	<div class="conteiner">
	<div class="left">
	<img src="<?php echo realpath(Yii::app()->basePath.'/../image/px.png'); ?>">
	</div>
	<div class="center">
		<?php echo CHtml::submitButton($model->isNewRecord ? 'Create' : 'Save', array('class'=>'form_button')); ?>
	</div>
	</div>

<?php $this->endWidget(); ?>

</div><!-- form -->

admin/protected/modules/catalog/views/catalog/create.php
<?php
/* @var $this CatalogController */
/* @var $model Catalog */

?>
<div class="conteiner">
<div class="left2">
				</div>
				<div class="center2">
<?php echo $this->renderPartial('_form', array('model'=>$model)); ?>
</div>
</div>	

admin/protected/modules/catalog/views/catalog/index.php
<?php
/* @var $this CatalogController */
/* @var $dataProvider CActiveDataProvider */
?><div class="conteiner">
<div class="left2">
				</div>
				<div class="center2">
	<div class="conteiner">
						<div class="center">
							<div class="statistics">Всего категорий: <strong>10</strong></div>
							<div class="statistics">Опубликованных категорий: <strong>9</strong></div>
						</div>
						<div class="right">
							<a href="<?php echo CHtml::normalizeUrl(array('catalog/create'))?>" class="add_new">Добавить категорию</a>
						</div>
					</div>
					
					<div class="otstup conteiner"></div>
<?php echo'		<div class="conteiner">
						<table>
							<thead>
								<tr>
									<th class="position">Позиция</th>
									<th class="name_menu">Название</th>
									<th class="actions">Действия</th>
								</tr>
							</thead>
							<tbody>';
for($i=0;$i<count($catalogs);$i++){
	echo $this->renderPartial('_catalogLine', array('catalog'=>$catalogs[$i], 'num'=>$i+1));
}								
				echo'			</tbody>
						</table>
					</div>';?>
					
					<div class="conteiner">
						<div class="postr">
							<a href="#" class="a str_a">1</a>
							<a href="#" class="str_a">2</a>
							<a href="#" class="str_a">3</a>
							<a href="#" class="str_a">4</a>
							<a href="#" class="str_a">5</a>
							<span>...</span>
							<a href="#" class="str_a">7</a>					
						</div>
					</div>
					<div class="conteiner">
						<div class="right">
							<a href="<?php echo CHtml::normalizeUrl(array('/catalog/ProductType/index'))?>" class="add_new">Конфигурация</a>
						</div>
					</div>
					</div>
					</div>
					

admin/protected/modules/catalog/views/catalog/update.php
<?php
/* @var $this CatalogController */
/* @var $model Catalog */
?>
<div class="conteiner">
<div class="left2">
				<?php $this->widget('application.components.leftMenu', array('menu'=>CatalogModule::leftMenu())); ?>
				<?php $this->widget('application.components.leftMenu', array('menu'=>CatalogModule::getCategoryMenu())); ?>
				</div>
				<div class="center2">
<h1>Редактирровать каталог <?php echo $model->name; ?></h1>

<?php echo $this->renderPartial('_form', array('model'=>$model)); ?>
</div>
</div>